spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/seguradora?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}

  security:
    user:
      name: ${SPRING_SECURITY_USER:admin}
      password: ${SPRING_SECURITY_PASSWORD:admin123}

    token:
      secret: ${TOKEN_SECRET:my-secret-key}

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    filter: true
    # Remove a configuração oauth2-redirect-url se não estiver usando OAuth2
  packages-to-scan: br.dev.paulowolfgang.gestao_apolices
  paths-to-match: /api/v1/**
  show-actuator: false
  writer-with-default-pretty-printer: true
  # Desabilita CSRF para o Swagger
  disable-swagger-default-url: true

messages:
  basename: messages/messages
  encoding: UTF-8
  fallback-to-system-locale: false