spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/seguradora?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}

  security:
    user:
      name: ${SPRING_SECURITY_USER:admin}
      password: ${SPRING_SECURITY_PASSWORD:admin123}

    token:
      secret: ${TOKEN_SECRET:my-secret-key}

messages:
  basename: messages/messages
  encoding: UTF-8
  fallback-to-system-locale: false
